config/routes.rb
PigHouse::Application.routes.draw do
  resources :pigs

  root :to => 'pigs#index'

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  # Restricciones
  validates :date, :born, :live, :dead, :mummified, :adopted, :low,
    :presence => true
  validates :born, :live, :dead, :mummified, :adopted, :low,
    :numericality => {:only_integer => true},
    :allow_nil => true, :allow_blank => true
  validates_date :date, :allow_nil => true, :allow_blank => true

  # Relaciones
  belongs_to :pig

  def initialize(attributes = nil)
    super(attributes)

    self.born ||= 0
    self.live ||= 0
    self.dead ||= 0
    self.mummified ||= 0
    self.adopted ||= 0
    self.low ||= 0
  end
end

app/models/pig.rb
class Pig < ActiveRecord::Base
  # Constantes
  STATUSES = {
    :pregnant => 'P',
    :ready => 'R',
    :served => 'S',
    :indisposed => 'I'
  }.with_indifferent_access.freeze

  # Restricciones
  validates :tag, :presence => true, :uniqueness => true
  validates :status, :presence => true, :length => { :maximum => 1 },
    :allow_blank => true, :allow_nil => true
  validates :tag, :father, :mother, :genetics, :group, :location,
    :length => { :maximum => 255 }, :allow_blank => true, :allow_nil => true
  validates :status, :inclusion => { :in => STATUSES.values },
    :allow_blank => true, :allow_nil => true
  validates_date :birth, :next_heat, :allow_blank => true, :allow_nil => true

  # Relaciones
  has_many :services, :dependent => :destroy, :inverse_of => :pig,
    :order => "#{Service.table_name}.date ASC"
  has_many :deliveries, :dependent => :destroy, :inverse_of => :pig,
    :order => "#{Delivery.table_name}.date ASC"
  has_many :weanings, :dependent => :destroy, :inverse_of => :pig,
    :order => "#{Weaning.table_name}.date ASC"

  accepts_nested_attributes_for :services, :allow_destroy => true,
    :reject_if => proc { |attributes| attributes['date'].blank? }
  accepts_nested_attributes_for :deliveries, :allow_destroy => true,
    :reject_if => proc { |attributes| attributes['date'].blank? }
  accepts_nested_attributes_for :weanings, :allow_destroy => true,
    :reject_if => proc { |attributes| attributes['date'].blank? }

  def initialize(attributes = nil)
    super(attributes)

    self.status ||= STATUSES[:ready]
  end

  def next_expected_delivery_date(force_recalculate = false)
    if force_recalculate || @expected_delivery_date.blank?
      last_service_date = self.services.reject(&:new_record?).last.try(:date)
      with_current_service = last_service_date &&
        last_service_date > 120.days.ago.to_date

      if (self.pregnant? || self.served?) && with_current_service
        @expected_delivery_date = last_service_date + 111.days
      else
        @expected_delivery_date = nil
      end

      if @expected_delivery_date && @expected_delivery_date >= Date.today
        @expected_delivery_date
      end
    else
      @expected_delivery_date
    end
  end

  def status_text
    I18n.t(STATUSES.invert[self.status], :scope => [:view, :pigs, :status])
  end

  STATUSES.each do |status, values|
    define_method(:"#{status}?") { self.status == values }
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
  # Restricciones
  validates :date, :presence => true
  validates :stallion, :length => { :maximum => 255 }, :allow_blank => true,
    :allow_nil => true
  validates_date :date, :allow_nil => true, :allow_blank => true

  # Relaciones
  belongs_to :pig
end

app/models/weaning.rb
class Weaning < ActiveRecord::Base
  # Restricciones
  validates :date, :weaned, :nursed_weaned, :age, :average_weight,
    :presence => true
  validates :weaned, :nursed_weaned, :age,
    :numericality => {:only_integer => true},
    :allow_nil => true, :allow_blank => true
  validates :average_weight, :allow_nil => true, :allow_blank => true,
    :numericality => { :greater_than => 0, :less_than => 100 }
  validates_date :date, :allow_nil => true, :allow_blank => true

  # Relaciones
  belongs_to :pig

  def initialize(attributes = nil)
    super(attributes)

    self.weaned ||= 0
    self.nursed_weaned ||= 0
    self.age ||= 0
    self.average_weight ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Cualquier excepción no contemplada es capturada por esta función. Se utiliza
  # para mostrar un mensaje de error personalizado
  rescue_from Exception do |exception|
    begin
      @title = t :'errors.title'

      unless response.redirect_url
        render :template => 'shared/show_error', :locals => {:error => exception}
      end

    # En caso que la presentación misma de la excepción no salga como se espera
    rescue => ex
      STDERR << "#{ex.class}: #{ex.message}\n\n"
      ex.backtrace.each { |l| STDERR << "#{l}\n" }
    end
  end
end

app/controllers/pigs_controller.rb
class PigsController < ApplicationController
  # GET /pigs
  # GET /pigs.xml
  def index
    @title = t :'view.pigs.index_title'
    @pigs = Pig.order('tag ASC').paginate(
      :page => params[:page],
      :per_page => APP_LINES_PER_PAGE
    )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pigs }
    end
  end

  # GET /pigs/1
  # GET /pigs/1.xml
  def show
    @title = t :'view.pigs.show_title'
    @pig = Pig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pig }
    end
  end

  # GET /pigs/new
  # GET /pigs/new.xml
  def new
    @title = t :'view.pigs.new_title'
    @pig = Pig.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pig }
    end
  end

  # GET /pigs/1/edit
  def edit
    @title = t :'view.pigs.edit_title'
    @pig = Pig.find(params[:id])
  end

  # POST /pigs
  # POST /pigs.xml
  def create
    @title = t :'view.pigs.new_title'
    @pig = Pig.new(params[:pig])

    respond_to do |format|
      if @pig.save
        format.html { redirect_to(pigs_path, :notice => t(:'view.pigs.correctly_created')) }
        format.xml  { render :xml => @pig, :status => :created, :location => @pig }
      else
        format.html { render :action => :new }
        format.xml  { render :xml => @pig.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pigs/1
  # PUT /pigs/1.xml
  def update
    @title = t :'view.pigs.edit_title'
    @pig = Pig.find(params[:id])

    respond_to do |format|
      if @pig.update_attributes(params[:pig])
        format.html { redirect_to(pigs_path, :notice => t(:'view.pigs.correctly_updated')) }
        format.xml  { head :ok }
      else
        format.html { render :action => :edit }
        format.xml  { render :xml => @pig.errors, :status => :unprocessable_entity }
      end
    end

  rescue ActiveRecord::StaleObjectError
    flash.alert = t :'view.pigs.stale_object_error'
    redirect_to edit_pig_url(@pig)
  end

  # DELETE /pigs/1
  # DELETE /pigs/1.xml
  def destroy
    @pig = Pig.find(params[:id])
    @pig.destroy

    respond_to do |format|
      format.html { redirect_to(pigs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_stylesheets
    sheets = ['common']
    sheets |= calendar_date_select_stylesheets(:style => 'silver').to_a
    sheets << {:cache => 'main'}

    stylesheet_link_tag *sheets
  end

  def default_javascripts
    libs = [:defaults]
    libs |= calendar_date_select_javascripts(:locale => :es).to_a
    libs << {:cache => 'main'}

    javascript_include_tag *libs
  end

  # Devuelve los mensajes de error con etiquetas HTML
  def show_error_messages(model)
    unless model.errors.empty?
      render :partial => 'shared/error_messages', :locals => { :model => model }
    end
  end

  # Devuelve el HTML con los links para navegar una lista paginada
  #
  # * _objects_:: Objetos con los que se genera la lista paginada
  def pagination_links(objects)
    previous_label = "&laquo; #{t :'label.previous'}".html_safe
    next_label = "#{t :'label.next'} &raquo;".html_safe

    result = will_paginate objects, :previous_label => previous_label,
      :next_label => next_label, :inner_window => 1, :outer_window => 1

    result ||= content_tag(:div, content_tag(:span, previous_label,
        :class => 'disabled prev_page') + content_tag(:em, 1) +
        content_tag(:span, next_label, :class => 'disabled next_page'),
      :class => :pagination)

    result
  end
end

app/helpers/pigs_helper.rb
module PigsHelper
  def select_pig_status_field(form)
    statuses = Pig::STATUSES.map do |s, v|
      [I18n.t(s, :scope => [:view, :pigs, :status]), v]
    end

    form.select :status, statuses, :prompt => true
  end

  def show_next_expected_delivery_date
    t(
      :next_expected_delivery_date,
      :date => l(@pig.next_expected_delivery_date, :format => :long),
      :scope => [:view, :pigs]
    )
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><%= [t(:app_name), @title].compact.join(' | ') %></title>
  <%= default_stylesheets %>
  <%= default_javascripts %>
  <%= csrf_meta_tag %>
  <%= javascript_tag do %>
    <%= yield :js_extra %>
  <% end %>
</head>
<body>
  <div id="loading" style="display: none;">
    <p><%= t(:'messages.loading') %></p>
  </div>
  <div id="main_menu">
    <%= render :partial => 'shared/menu' %>
  </div>
  <div id="main_container">
    <%= yield %>
  </div>
  <%= render :partial => 'shared/notice' if flash.notice %>
  <%= render :partial => 'shared/alert' if flash.alert %>
</body>
</html>

app/views/pigs/_form.html.erb
<%= form_for(@pig, :html => {:id => :pig_form}) do |f| %>
  <%= show_error_messages(@pig) %>

  <div class="form_with_column_container">
    <div class="form_left">
      <div class="field">
        <%= f.label :tag %>
        <%= f.text_field :tag, :maxlength => 255 %>
      </div>
      <div class="field">
        <%= f.label :father %>
        <%= f.text_field :father, :maxlength => 255 %>
      </div>
      <div class="field">
        <%= f.label :mother %>
        <%= f.text_field :mother, :maxlength => 255 %>
      </div>
      <div class="field">
        <%= f.label :genetics %>
        <%= f.text_field :genetics, :maxlength => 255 %>
      </div>
      <div class="field">
        <%= f.label :status %>
        <%= select_pig_status_field(f) %>
      </div>
    </div>

    <div class="form_right">
      <div class="field">
        <%= f.label :birth %>
        <%= f.calendar_date_select :birth %>
      </div>
      <div class="field">
        <%= f.label :next_heat %>
        <%= f.calendar_date_select :next_heat %>
      </div>
      <div class="field">
        <%= f.label :group %>
        <%= f.text_field :group, :maxlength => 255 %>
      </div>
      <div class="field">
        <%= f.label :location %>
        <%= f.text_field :location, :maxlength => 255 %>
      </div>
    </div>
  </div>

  <h2 class="subtitle">
    <%= Pig.human_attribute_name :deliveries, :count => @pig.deliveries.size %>
  </h2>

  <table id="deliveries" class="summary">
    <thead>
      <tr>
        <th><%= Delivery.human_attribute_name :date %></th>
        <th><%= Delivery.human_attribute_name :born %></th>
        <th><%= Delivery.human_attribute_name :live %></th>
        <th><%= Delivery.human_attribute_name :dead %></th>
        <th><%= Delivery.human_attribute_name :mummified %></th>
        <th><%= Delivery.human_attribute_name :adopted %></th>
        <th><%= Delivery.human_attribute_name :low %></th>
      </tr>
    </thead>
    <tbody>
      <% @pig.deliveries.build %>
      <%= f.fields_for :deliveries do |d_f| %>
        <tr>
          <td><%= d_f.calendar_date_select :date %><%= d_f.hidden_field :id %></td>
          <td><%= d_f.text_field :born, :maxlength => 10 %></td>
          <td><%= d_f.text_field :live, :maxlength => 10 %></td>
          <td><%= d_f.text_field :dead, :maxlength => 10 %></td>
          <td><%= d_f.text_field :mummified, :maxlength => 10 %></td>
          <td><%= d_f.text_field :adopted, :maxlength => 10 %></td>
          <td><%= d_f.text_field :low, :maxlength => 10 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="subtitle">
    <%= Pig.human_attribute_name :weanings, :count => @pig.weanings.size %>
  </h2>

  <table id="weanings" class="summary">
    <thead>
      <tr>
        <th><%= Weaning.human_attribute_name :date %></th>
        <th><%= Weaning.human_attribute_name :weaned %></th>
        <th><%= Weaning.human_attribute_name :nursed_weaned %></th>
        <th><%= Weaning.human_attribute_name :age %></th>
        <th><%= Weaning.human_attribute_name :average_weight %></th>
      </tr>
    </thead>
    <tbody>
      <% @pig.weanings.build %>
      <%= f.fields_for :weanings do |w_f| %>
        <tr>
          <td><%= w_f.calendar_date_select :date %><%= w_f.hidden_field :id %></td>
          <td><%= w_f.text_field :weaned, :maxlength => 10 %></td>
          <td><%= w_f.text_field :nursed_weaned, :maxlength => 10 %></td>
          <td><%= w_f.text_field :age, :maxlength => 10 %></td>
          <td><%= w_f.text_field :average_weight, :maxlength => 10 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2 class="subtitle">
    <%= Pig.human_attribute_name :services, :count => @pig.services.size %>
  </h2>

  <table id="services" class="summary">
    <thead>
      <tr>
        <th><%= Service.human_attribute_name :date %></th>
        <th><%= Service.human_attribute_name :stallion %></th>
      </tr>
    </thead>
    <tbody>
      <% @pig.services.build %>
      <%= f.fields_for :services do |s_f| %>
        <tr>
          <td><%= s_f.calendar_date_select :date %><%= s_f.hidden_field :id %></td>
          <td><%= s_f.text_field :stallion, :maxlength => 255 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @pig.next_expected_delivery_date %>
    <div class="information">
      <span><%= show_next_expected_delivery_date %></span>
    </div>
  <% end %>

  <div class="actions">
    <%= f.hidden_field :lock_version %>
    <%= f.submit %>
  </div>
<% end %>

app/views/pigs/edit.html.erb
<%= render 'form' %>

<nav class="links">
  <%= link_to t(:'label.show'), @pig %> |
  <%= link_to t(:'label.list'), pigs_path %>
</nav>

app/views/pigs/index.html.erb
<table class="list">
  <thead>
    <tr>
      <th><%= Pig.human_attribute_name :tag %></th>
      <th><%= Pig.human_attribute_name :birth %></th>
      <th><%= Pig.human_attribute_name :next_heat %></th>
      <th><%= Pig.human_attribute_name :genetics %></th>
      <th><%= Pig.human_attribute_name :group %></th>
      <th><%= Pig.human_attribute_name :location %></th>
      <th><%= Pig.human_attribute_name :status %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pigs.each do |pig| %>
      <tr class="<%= cycle(:even, :odd) %>">
        <td><%= pig.tag %></td>
        <td><%= l(pig.birth) if pig.birth %></td>
        <td><%= l(pig.next_heat) if pig.next_heat %></td>
        <td><%= pig.genetics %></td>
        <td><%= pig.group %></td>
        <td><%= pig.location %></td>
        <td><%= pig.status_text %></td>
        <td><%= link_to t(:'label.show'), pig %></td>
        <td><%= link_to t(:'label.edit'), edit_pig_path(pig) %></td>
        <td><%= button_to t(:'label.delete'), pig,
          :confirm => t(:'messages.confirmation'), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<nav class="links">
  <%= pagination_links(@pigs) %>
  <%= link_to t(:'label.new'), new_pig_path %>
</nav>

app/views/pigs/new.html.erb
<%= render 'form' %>

<nav class="links">
  <%= link_to t(:'label.list'), pigs_path %>
</nav>

app/views/pigs/show.html.erb
<div id="pig_data" class="readonly_data">
  <p>
    <b><%= Pig.human_attribute_name :tag %>:</b>
    <%= @pig.tag %>
  </p>

  <p>
    <b><%= Pig.human_attribute_name :mother %>:</b>
    <%= @pig.mother %>
  </p>

  <p>
    <b><%= Pig.human_attribute_name :father %>:</b>
    <%= @pig.father %>
  </p>

  <p>
    <b><%= Pig.human_attribute_name :birth %>:</b>
    <%= l(@pig.birth, :format => :long) if @pig.birth %>
  </p>

  <p>
    <b><%= Pig.human_attribute_name :next_heat %>:</b>
    <%= l(@pig.next_heat, :format => :long) if @pig.next_heat %>
  </p>

  <p>
    <b><%= Pig.human_attribute_name :genetics %>:</b>
    <%= @pig.genetics %>
  </p>

  <p>
    <b><%= Pig.human_attribute_name :group %>:</b>
    <%= @pig.group %>
  </p>

  <p>
    <b><%= Pig.human_attribute_name :location %>:</b>
    <%= @pig.location %>
  </p>

  <p>
    <b><%= Pig.human_attribute_name :status %>:</b>
    <%= @pig.status_text %>
  </p>

  <% unless @pig.deliveries.empty? %>
    <h2 class="subtitle">
      <%= Pig.human_attribute_name :deliveries, :count => @pig.deliveries.size %>
    </h2>

    <table id="deliveries" class="summary">
      <thead>
        <tr>
          <th><%= Delivery.human_attribute_name :date %></th>
          <th><%= Delivery.human_attribute_name :born %></th>
          <th><%= Delivery.human_attribute_name :live %></th>
          <th><%= Delivery.human_attribute_name :dead %></th>
          <th><%= Delivery.human_attribute_name :mummified %></th>
          <th><%= Delivery.human_attribute_name :adopted %></th>
          <th><%= Delivery.human_attribute_name :low %></th>
        </tr>
      </thead>
      <tbody>
        <% @pig.deliveries.each do |delivery| %>
          <tr>
            <td><%= l(delivery.date) %></td>
            <td><%= delivery.born %></td>
            <td><%= delivery.live %></td>
            <td><%= delivery.dead %></td>
            <td><%= delivery.mummified %></td>
            <td><%= delivery.adopted %></td>
            <td><%= delivery.low %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% unless @pig.weanings.empty? %>
    <h2 class="subtitle">
      <%= Pig.human_attribute_name :weanings, :count => @pig.weanings.size %>
    </h2>

    <table id="weanings" class="summary">
      <thead>
        <tr>
          <th><%= Weaning.human_attribute_name :date %></th>
          <th><%= Weaning.human_attribute_name :weaned %></th>
          <th><%= Weaning.human_attribute_name :nursed_weaned %></th>
          <th><%= Weaning.human_attribute_name :age %></th>
          <th><%= Weaning.human_attribute_name :average_weight %></th>
        </tr>
      </thead>
      <tbody>
        <% @pig.weanings.each do |weaning| %>
          <tr>
            <td><%= l(weaning.date) %></td>
            <td><%= weaning.weaned %></td>
            <td><%= weaning.nursed_weaned %></td>
            <td><%= weaning.age %></td>
            <td><%= weaning.average_weight %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% unless @pig.services.empty? %>
    <h2 class="subtitle">
      <%= Pig.human_attribute_name :services, :count => @pig.services.size %>
    </h2>

    <table id="services" class="summary">
      <thead>
        <tr>
          <th><%= Service.human_attribute_name :date %></th>
          <th><%= Service.human_attribute_name :stallion %></th>
        </tr>
      </thead>
      <tbody>
        <% @pig.services.each do |service| %>
          <tr>
            <td><%= l(service.date) %></td>
            <td><%= service.stallion || '-' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% if @pig.next_expected_delivery_date %>
    <div class="information">
      <span><%= show_next_expected_delivery_date %></span>
    </div>
  <% end %>
</div>

<nav class="links">
  <%= link_to t(:'label.edit'), edit_pig_path(@pig) %> |
  <%= link_to t(:'label.list'), pigs_path %>
</nav>

app/views/shared/_alert.html.erb
<div id="alert">
  <p><%= flash.alert %></p>
  <div id="close_alert"><%= link_to_function 'X', "$('alert').fade()",
    :title => t(:'label.close') %></div>
</div>
<%= javascript_tag "Element.fade.delay(7, 'alert');" %>

app/views/shared/_error_messages.html.erb
<div id="error_explanation">
  <h2>
    <%= t(:header, :scope => [:errors, :template],
      :model => model.class.model_name.human, :count => model.errors.count) %>
  </h2>

  <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_menu.html.erb
<% current_controller = controller.controller_name.to_sym %>
<nav id="menu_links">
  <ul>
    <%= content_tag(:li, link_to(t(:pigs, :scope => :menu), pigs_path),
      :class => (:selected if current_controller == :pigs)) %>
  </ul>
</nav>

app/views/shared/_notice.html.erb
<div id="notice">
  <p><%= flash.notice %></p>
  <div id="close_notice"><%= link_to_function 'X', "$('notice').fade()",
    :title => t(:'label.close') %></div>
</div>
<%= javascript_tag "Element.fade.delay(7, 'notice');" %>

app/views/shared/show_error.html.erb
<div id="unexpected_error" style="margin-bottom: 1em;">
  <div id="error_header">
    <h1><%= t(:'errors.header_message') %></h1>
  </div>

  <div id="error_body">
    <p><%= t(:'errors.apologies_for_the_inconvenience') %></p>
  </div>
</div>

<% unless Rails.env.production? %>
  <%= link_to_function t(:'errors.show_details'),
    "Effect.SlideDown('error_details'); this.hide()", :id => 'show_link' %>
  <div style="display: none;" id="error_details">
    <div>
      <%= link_to_function t(:'errors.hide_details'),
        "Effect.SlideUp('error_details'); $('show_link').appear()" %>
      <!-- Final -->
      <h2 style="margin: 1em 0em;"><%= error.message %></h2>
      <h3>Backtrace:</h3>
      <pre style="margin-top: .5em;"><%= error.backtrace.join("\n") %></pre>

      <% unless params.empty? %>
      <h3 style="margin-top: 1em;">Parameters:</h3>
      <pre style="margin-top: .5em;"><%= params.inspect %></pre>
      <% end %>
      <div style="clear: both;"></div>
    </div>
  </div>
<% end %>